name: linux-x64

on: 
  workflow_dispatch

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: |
          rm -rf /opt/hostedtoolcache
      - name: Checkout sources
        run: |
          git clone -b chromium/6727 https://github.com/google/angle .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Release --args="is_debug=false target_cpu=\"x64\" angle_build_all=false is_component_build = false angle_enable_d3d9 = false angle_enable_d3d11 = false angle_enable_gl = false angle_enable_null = false angle_enable_metal = false angle_enable_vulkan = true angle_enable_essl = false angle_enable_glsl = true"
          autoninja -C out/Release
      - name: Pack
        run: |
          mkdir angle-linux-x64
          mkdir angle-linux-x64/dist
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          rm -rf out/Release/args.gn
          rm -rf out/Release/build.ninja
          rm -rf out/Release/build.ninja.d
          rm -rf out/Release/toolchain.ninja
          find out/Release -name "*.TOC" -delete
          mv -f out/Release/* angle-linux-x64/dist/
          cp -rf include angle-linux-x64/
          find angle-linux-x64 -name ".clang-format" -delete
          find angle-linux-x64 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angle-linux-x64
          path: angle-linux-x64
